### ISSUE TITLE
PeakPickerLearn

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/EvoNet#10]
### Description
Peak picking and integration using deep learning

### Objectives
- [ ] identification of all peaks
- [ ] correct baseline integration of all peaks
- [ ] smoothing of spurious points, interpolation of saturated peaks, interpolation of cutoff peaks

### Validation
- 99% identification of all peaks in a chromatogram
- correct area/height estimation of saturated peaks
- correct area/height estimation of partially cutoff peaks

### Tests and checks
- 100% test accuracy on a single peak
- 100% test accuracy on multiple peaks
