### ISSUE TITLE
NodeIntegration

### ISSUE THREAD

**Issue by dmccloskey** [dmccloskey/EvoNet#47]
### Description
Allow for multiple input integration strategies such as Sum, Product, and Max

### TODOs
- [x] NodeIntegration enum class
- [x] Tests and update of all other code for NodeIntegration
- [x] input_ internal parameter with getters/setters
- [x] Tests for input_
- [x] update FP with NodeIntegration options
- [x] Tests for FP with NodeIntegration options
- [x] update BP with NodeIntegration options
- [x] Tests for BP with NodeIntegration options
- [x] update weightUpdate with NodeIntegration options
- [x] Tests for weightUpdate with NodeIntegration options
